
package br.com.comven.corews.transacao.client.prepago.cpf;

import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.springframework.cache.CacheManager;

import br.com.comven.corews.transacao.util.enumerator.EParametro;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS_Controle_Int_COMVEN", targetNamespace = "Controle_Interface_COMVEN", wsdlLocation = "http://www.autenticis.com.br/teste_ws_int_comven_cpf/service.asmx?wsdl")
public class WSControleIntCOMVEN extends Service {
	
    private static URL WSCONTROLEINTCOMVEN_WSDL_LOCATION = null;
    private final static WebServiceException WSCONTROLEINTCOMVEN_EXCEPTION = null;
    private final static QName WSCONTROLEINTCOMVEN_QNAME = new QName("Controle_Interface_COMVEN", "WS_Controle_Int_COMVEN");
    private final static Logger logger = Logger.getLogger(br.com.comven.corews.transacao.client.prepago.cpf.WSControleIntCOMVEN.class.getName());
    
    public static void setWSUrl(CacheManager cacheManager) {
    	
    	 URL url = null;
         String urlWS = null;
         
         try {
         	
         	urlWS = cacheManager.getCache(EParametro.NAME).get(EParametro.WS_PRE_PAGO_CPF.getCodigo()).get().toString();
            url = new URL(urlWS);
             
            
         } catch (Exception e) {
             logger.warning("Failed to create URL for the wsdl Location: " + urlWS);
             logger.warning(e.getMessage());
         }
        
         WSCONTROLEINTCOMVEN_WSDL_LOCATION = url;
    }

    public WSControleIntCOMVEN() {
        super(__getWsdlLocation(), WSCONTROLEINTCOMVEN_QNAME);
    }

    public WSControleIntCOMVEN(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCONTROLEINTCOMVEN_QNAME, features);
    }

    public WSControleIntCOMVEN(URL wsdlLocation) {
        super(wsdlLocation, WSCONTROLEINTCOMVEN_QNAME);
    }

    public WSControleIntCOMVEN(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCONTROLEINTCOMVEN_QNAME, features);
    }

    public WSControleIntCOMVEN(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSControleIntCOMVEN(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSControleIntCOMVENSoap
     */
    @WebEndpoint(name = "WS_Controle_Int_COMVENSoap")
    public WSControleIntCOMVENSoap getWSControleIntCOMVENSoap() {
        return super.getPort(new QName("Controle_Interface_COMVEN", "WS_Controle_Int_COMVENSoap"), WSControleIntCOMVENSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSControleIntCOMVENSoap
     */
    @WebEndpoint(name = "WS_Controle_Int_COMVENSoap")
    public WSControleIntCOMVENSoap getWSControleIntCOMVENSoap(WebServiceFeature... features) {
        return super.getPort(new QName("Controle_Interface_COMVEN", "WS_Controle_Int_COMVENSoap"), WSControleIntCOMVENSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCONTROLEINTCOMVEN_EXCEPTION!= null) {
            throw WSCONTROLEINTCOMVEN_EXCEPTION;
        }
        return WSCONTROLEINTCOMVEN_WSDL_LOCATION;
    }

}
